//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MetaBuilder.WinUI.Metabuilder.co.za.Licencing {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MetabuilderLicencingSoap", Namespace="http://www.metabuilder.co.za/Licencing/")]
    public partial class MetabuilderLicencing : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LicenceUsageOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckVersionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MetabuilderLicencing() {
            this.Url = global::MetaBuilder.WinUI.Properties.Settings.Default.MetaBuilder_Metabuilder_co_za_Licencing_MetabuilderLicencing;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LicenceUsageCompletedEventHandler LicenceUsageCompleted;
        
        /// <remarks/>
        public event CheckVersionCompletedEventHandler CheckVersionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.metabuilder.co.za/Licencing/LicenceUsage", RequestNamespace="http://www.metabuilder.co.za/Licencing/", ResponseNamespace="http://www.metabuilder.co.za/Licencing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LicenceUsage(string type, string key, string username, string userDomainName) {
            object[] results = this.Invoke("LicenceUsage", new object[] {
                        type,
                        key,
                        username,
                        userDomainName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LicenceUsageAsync(string type, string key, string username, string userDomainName) {
            this.LicenceUsageAsync(type, key, username, userDomainName, null);
        }
        
        /// <remarks/>
        public void LicenceUsageAsync(string type, string key, string username, string userDomainName, object userState) {
            if ((this.LicenceUsageOperationCompleted == null)) {
                this.LicenceUsageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLicenceUsageOperationCompleted);
            }
            this.InvokeAsync("LicenceUsage", new object[] {
                        type,
                        key,
                        username,
                        userDomainName}, this.LicenceUsageOperationCompleted, userState);
        }
        
        private void OnLicenceUsageOperationCompleted(object arg) {
            if ((this.LicenceUsageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LicenceUsageCompleted(this, new LicenceUsageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.metabuilder.co.za/Licencing/CheckVersion", RequestNamespace="http://www.metabuilder.co.za/Licencing/", ResponseNamespace="http://www.metabuilder.co.za/Licencing/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckVersion(string currentVersion) {
            object[] results = this.Invoke("CheckVersion", new object[] {
                        currentVersion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckVersionAsync(string currentVersion) {
            this.CheckVersionAsync(currentVersion, null);
        }
        
        /// <remarks/>
        public void CheckVersionAsync(string currentVersion, object userState) {
            if ((this.CheckVersionOperationCompleted == null)) {
                this.CheckVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckVersionOperationCompleted);
            }
            this.InvokeAsync("CheckVersion", new object[] {
                        currentVersion}, this.CheckVersionOperationCompleted, userState);
        }
        
        private void OnCheckVersionOperationCompleted(object arg) {
            if ((this.CheckVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckVersionCompleted(this, new CheckVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LicenceUsageCompletedEventHandler(object sender, LicenceUsageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LicenceUsageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LicenceUsageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CheckVersionCompletedEventHandler(object sender, CheckVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591