//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaBuilder.UIControls.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.metabuilder.co.za/RegistrationWS/Service.asmx")]
        public string MetaBuilder_UIControls_RegistrationWS_Service {
            get {
                return ((string)(this["MetaBuilder_UIControls_RegistrationWS_Service"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string View_ShowGrid {
            get {
                return ((string)(this["View_ShowGrid"]));
            }
            set {
                this["View_ShowGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HighQuality")]
        public string View_SmoothingMode {
            get {
                return ((string)(this["View_SmoothingMode"]));
            }
            set {
                this["View_SmoothingMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string View_SnapToGrid {
            get {
                return ((string)(this["View_SnapToGrid"]));
            }
            set {
                this["View_SnapToGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files\\Discon Specialists\\MetaBuilder\\MetaData\\Symbols\\")]
        public string Paths_Symbols {
            get {
                return ((string)(this["Paths_Symbols"]));
            }
            set {
                this["Paths_Symbols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files\\Discon Specialists\\MetaBuilder\\MetaData\\Stencils\\")]
        public string Paths_Stencils {
            get {
                return ((string)(this["Paths_Stencils"]));
            }
            set {
                this["Paths_Stencils"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files\\Discon Specialists\\MetaBuilder\\MetaData\\Diagrams\\")]
        public string Paths_Diagrams {
            get {
                return ((string)(this["Paths_Diagrams"]));
            }
            set {
                this["Paths_Diagrams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files\\Discon Specialists\\MetaBuilder\\MetaData\\ArrowHeads\\")]
        public string Paths_ArrowHeads {
            get {
                return ((string)(this["Paths_ArrowHeads"]));
            }
            set {
                this["Paths_ArrowHeads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files\\Discon Specialists\\MetaBuilder\\MetaData\\Export\\")]
        public string Paths_Export {
            get {
                return ((string)(this["Paths_Export"]));
            }
            set {
                this["Paths_Export"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files\\Discon Specialists\\MetaBuilder\\MetaData\\DebugReports\\")]
        public string Paths_Debug {
            get {
                return ((string)(this["Paths_Debug"]));
            }
            set {
                this["Paths_Debug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files\\Discon Specialists\\MetaBuilder\\MetaData\\Thumbs\\")]
        public string Paths_Thumbnails {
            get {
                return ((string)(this["Paths_Thumbnails"]));
            }
            set {
                this["Paths_Thumbnails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DockRight")]
        public string FormLayout_MetaPropertyGrid {
            get {
                return ((string)(this["FormLayout_MetaPropertyGrid"]));
            }
            set {
                this["FormLayout_MetaPropertyGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DockLeft")]
        public string FormLayout_PropertyGrid {
            get {
                return ((string)(this["FormLayout_PropertyGrid"]));
            }
            set {
                this["FormLayout_PropertyGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DockBottom")]
        public string FormLayout_Output {
            get {
                return ((string)(this["FormLayout_Output"]));
            }
            set {
                this["FormLayout_Output"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DockLeft")]
        public string FormLayout_Stencils {
            get {
                return ((string)(this["FormLayout_Stencils"]));
            }
            set {
                this["FormLayout_Stencils"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DockLeft")]
        public string FormLayout_Navigator {
            get {
                return ((string)(this["FormLayout_Navigator"]));
            }
            set {
                this["FormLayout_Navigator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Deon Fourie")]
        public string General_UserFullname {
            get {
                return ((string)(this["General_UserFullname"]));
            }
            set {
                this["General_UserFullname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DF")]
        public string General_UserInitials {
            get {
                return ((string)(this["General_UserInitials"]));
            }
            set {
                this["General_UserInitials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DISCON Specialists")]
        public string General_Company {
            get {
                return ((string)(this["General_Company"]));
            }
            set {
                this["General_Company"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string Save_EnableAutosave {
            get {
                return ((string)(this["Save_EnableAutosave"]));
            }
            set {
                this["Save_EnableAutosave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DatabaseAndFileSystem")]
        public string Save_DefaultTarget {
            get {
                return ((string)(this["Save_DefaultTarget"]));
            }
            set {
                this["Save_DefaultTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string Versioning_AutoCheckoutAllShapes {
            get {
                return ((string)(this["Versioning_AutoCheckoutAllShapes"]));
            }
            set {
                this["Versioning_AutoCheckoutAllShapes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string Versioning_PurgeMinorVersions {
            get {
                return ((string)(this["Versioning_PurgeMinorVersions"]));
            }
            set {
                this["Versioning_PurgeMinorVersions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Program Files\\Discon Specialists\\MetaBuilder\\MetaData\\SourceFiles")]
        public string Paths_MetaData_SourceFiles {
            get {
                return ((string)(this["Paths_MetaData_SourceFiles"]));
            }
            set {
                this["Paths_MetaData_SourceFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string Save_AutosaveInterval {
            get {
                return ((string)(this["Save_AutosaveInterval"]));
            }
            set {
                this["Save_AutosaveInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string Versioning_PurgeMinorVersionsInterval {
            get {
                return ((string)(this["Versioning_PurgeMinorVersionsInterval"]));
            }
            set {
                this["Versioning_PurgeMinorVersionsInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string View_CanvasWidth {
            get {
                return ((string)(this["View_CanvasWidth"]));
            }
            set {
                this["View_CanvasWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string View_CanvasHeight {
            get {
                return ((string)(this["View_CanvasHeight"]));
            }
            set {
                this["View_CanvasHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string View_GridSize {
            get {
                return ((string)(this["View_GridSize"]));
            }
            set {
                this["View_GridSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string General_NumberOfUndoLevels {
            get {
                return ((string)(this["General_NumberOfUndoLevels"]));
            }
            set {
                this["General_NumberOfUndoLevels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=.\\sqlexpress;Integrated Security=true;database=MetaBuilder;Connection Rese" +
            "t=FALSE")]
        public string DB_LocalInstanceConnectionString {
            get {
                return ((string)(this["DB_LocalInstanceConnectionString"]));
            }
            set {
                this["DB_LocalInstanceConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=.\\sqlexpress;Integrated Security=true;database=MetaBuilder;Connection Rese" +
            "t=FALSE")]
        public string DB_SyncServerConnectionString {
            get {
                return ((string)(this["DB_SyncServerConnectionString"]));
            }
            set {
                this["DB_SyncServerConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string Save_PromptForDocumentPropertiesOnFirstSave {
            get {
                return ((string)(this["Save_PromptForDocumentPropertiesOnFirstSave"]));
            }
            set {
                this["Save_PromptForDocumentPropertiesOnFirstSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ID")]
        public string ID {
            get {
                return ((string)(this["ID"]));
            }
            set {
                this["ID"] = value;
            }
        }
    }
}
